import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CalendarDays, CheckCircle2, Clock, FileText, LogOut, Plus, Trash2, Upload, Users, Wallet, Car, Plane, LockKeyhole, Home, Euro, Image as ImageIcon} from 'lucide-react';
import './style.css';

const DEFAULT_ADMIN = 'info@actilampe.ch';
const DEFAULT_PASSWORD = '1234';
const STORE = 'zyvora-suite-v1';

const swissHolidays2026 = ['2026-01-01','2026-01-02','2026-04-03','2026-04-06','2026-05-14','2026-05-25','2026-08-01','2026-12-25'];

const initialData = {
  employees: [
    {id:'emp-admin', name:'Admin Actilampe', email:DEFAULT_ADMIN, role:'admin', password:DEFAULT_PASSWORD, mustChangePassword:true, active:true, createdAt:new Date().toISOString()},
    {id:'emp-1', name:'Hugo Mendes', email:'mendes.hugo@actilampe.ch', role:'employee', password:DEFAULT_PASSWORD, mustChangePassword:true, active:true, createdAt:new Date().toISOString()}
  ],
  projects: ['Chantier Villa', 'Dépannage client', 'Bureau / Administration', 'Restaurant', 'Appartement'],
  timeEntries: [],
  absences: [],
  expenses: [],
  payslips: [],
  mileage: [],
  settings: {holidays: swissHolidays2026}
};

function loadData(){
  try { return JSON.parse(localStorage.getItem(STORE)) || initialData; } catch { return initialData; }
}
function saveData(data){ localStorage.setItem(STORE, JSON.stringify(data)); }
function uid(){ return Math.random().toString(36).slice(2) + Date.now().toString(36); }
function today(){ return new Date().toISOString().slice(0,10); }
function weekStart(d = new Date()) { const x = new Date(d); const day = x.getDay() || 7; x.setDate(x.getDate() - day + 1); return x.toISOString().slice(0,10); }
function monthKey(date){ return String(date || '').slice(0,7); }
function isHoliday(date, data){ return data.settings.holidays.includes(date); }
function downloadText(name, text, type='text/plain'){
  const blob = new Blob([text], {type}); const url = URL.createObjectURL(blob); const a = document.createElement('a');
  a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);
}
function fileToDataUrl(file){ return new Promise((resolve)=>{ const r=new FileReader(); r.onload=()=>resolve(r.result); r.readAsDataURL(file); }); }

function App(){
  const [data,setDataState] = useState(loadData());
  const [user,setUser] = useState(null);
  const [login,setLogin] = useState({email:DEFAULT_ADMIN,password:DEFAULT_PASSWORD});
  const [page,setPage] = useState('week');
  const [pw,setPw] = useState('');

  const setData = (next)=>{ const value = typeof next === 'function' ? next(data) : next; setDataState(value); saveData(value); };

  const doLogin = (e)=>{ e.preventDefault(); const found = data.employees.find(x=>x.email.toLowerCase()===login.email.toLowerCase() && x.password===login.password && x.active); if(found){ setUser(found); setPage(found.role==='admin'?'adminDashboard':'week'); } else alert('Email ou mot de passe incorrect.'); };
  const changePassword = (e)=>{ e.preventDefault(); if(pw.length < 4) return alert('Minimum 4 caractères.'); const updated = {...user,password:pw,mustChangePassword:false}; setData(d=>({...d, employees:d.employees.map(x=>x.id===user.id?updated:x)})); setUser(updated); };
  if(!user) return <Login login={login} setLogin={setLogin} doLogin={doLogin}/>;
  if(user.mustChangePassword) return <PasswordChange user={user} pw={pw} setPw={setPw} changePassword={changePassword}/>;

  const isAdmin = user.role==='admin';
  const pages = isAdmin ? [
    ['adminDashboard','Tableau admin',Home], ['week','Heures semaine',Clock], ['reports','Rapports',FileText], ['approval','Validation',CheckCircle2], ['employees','Employés',Users], ['absences','Vacances / congés',Plane], ['calendar','Calendrier absences',CalendarDays], ['expenses','Notes de frais',Wallet], ['mileage','Kilomètres',Car], ['payslips','Fiches de salaire',FileText]
  ] : [
    ['week','Heures semaine',Clock], ['reports','Mes rapports',FileText], ['absences','Vacances / congés',Plane], ['calendar','Calendrier absences',CalendarDays], ['expenses','Notes de frais',Wallet], ['mileage','Kilomètres',Car], ['payslips','Fiches de salaire',FileText]
  ];
  return <div className="app"><aside><div className="brand"><div className="logo">Z</div><div><b>Zyvora Suite</b><small>{user.name}</small></div></div>{pages.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={18}/>{label}</button>)}<button className="logout" onClick={()=>setUser(null)}><LogOut size={18}/>Déconnexion</button></aside><main><Render page={page} user={user} data={data} setData={setData}/></main></div>;
}
function Login({login,setLogin,doLogin}){ return <div className="login"><form onSubmit={doLogin} className="card loginCard"><div className="bigLogo">Z</div><h1>Zyvora Suite</h1><p>Gestion des heures, absences, frais, kilomètres et fiches de salaire.</p><label>Email</label><input value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><label>Mot de passe</label><input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="primary">Se connecter</button><small>Admin test : info@actilampe.ch / 1234<br/>Employé test : mendes.hugo@actilampe.ch / 1234</small></form></div>; }
function PasswordChange({user,pw,setPw,changePassword}){ return <div className="login"><form onSubmit={changePassword} className="card loginCard"><LockKeyhole size={42}/><h1>Changer le mot de passe</h1><p>Première connexion pour {user.email}</p><input type="password" placeholder="Nouveau mot de passe" value={pw} onChange={e=>setPw(e.target.value)}/><button className="primary">Enregistrer</button></form></div>; }
function Render(props){ const map={adminDashboard:AdminDashboard,week:WeekHours,reports:Reports,approval:Approval,employees:Employees,absences:Absences,calendar:AbsenceCalendar,expenses:Expenses,mileage:Mileage,payslips:Payslips}; const C=map[props.page]||WeekHours; return <C {...props}/>; }
function Header({title,desc}){return <><h1>{title}</h1><p className="muted">{desc}</p></>}
function AdminDashboard({data}){ const pending=data.timeEntries.filter(x=>x.status==='pending').length; const hours=data.timeEntries.reduce((a,b)=>a+Number(b.hours||0),0); const expenses=data.expenses.reduce((a,b)=>a+Number(b.amount||0),0); const active=data.employees.filter(x=>x.active).length; return <><Header title="Tableau de bord admin" desc="Vue globale de l'entreprise."/><div className="grid4"><Stat label="Employés actifs" val={active}/><Stat label="Heures saisies" val={hours.toFixed(1)}/><Stat label="À valider" val={pending}/><Stat label="Frais CHF" val={expenses.toFixed(2)}/></div><div className="card"><h2>Dernières heures</h2><Table rows={data.timeEntries.slice(-8).reverse()} cols={['date','employeeName','project','hours','status']}/></div></> }
function Stat({label,val}){return <div className="card stat"><span>{label}</span><b>{val}</b></div>}
function WeekHours({user,data,setData}){ const [form,setForm]=useState({date:today(),project:data.projects[0],hours:'8',overtime:'0',note:''}); const mine = data.timeEntries.filter(x=>user.role==='admin'||x.employeeId===user.id).filter(x=>x.date>=weekStart()); const submit=e=>{e.preventDefault(); const entry={id:uid(),...form,hours:Number(form.hours),overtime:Number(form.overtime||0),employeeId:user.id,employeeName:user.name,status:'pending',createdAt:new Date().toISOString(),holiday:isHoliday(form.date,data)}; setData(d=>({...d,timeEntries:[...d.timeEntries,entry]})); setForm({...form,hours:'8',overtime:'0',note:''});}; return <><Header title="Heures de la semaine" desc="Saisie par chantier/projet. Les jours fériés sont signalés automatiquement."/><form className="card formGrid" onSubmit={submit}><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><select value={form.project} onChange={e=>setForm({...form,project:e.target.value})}>{data.projects.map(p=><option key={p}>{p}</option>)}</select><input type="number" step="0.25" placeholder="Heures" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})}/><input type="number" step="0.25" placeholder="Heures sup." value={form.overtime} onChange={e=>setForm({...form,overtime:e.target.value})}/><input placeholder="Note" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><button className="primary"><Plus size={16}/>Ajouter</button></form><div className="card"><Table rows={mine} cols={['date','employeeName','project','hours','overtime','holiday','status','note']}/></div></> }
function Reports({user,data}){ const rows=data.timeEntries.filter(x=>user.role==='admin'||x.employeeId===user.id); const csv=()=>downloadText('rapport-heures.csv',['date;employe;projet;heures;heures_sup;statut;note',...rows.map(r=>`${r.date};${r.employeeName};${r.project};${r.hours};${r.overtime};${r.status};${r.note||''}`)].join('\n'),'text/csv'); const summary=Object.values(rows.reduce((a,r)=>{const k=r.employeeName+'-'+monthKey(r.date); a[k]??={employe:r.employeeName,mois:monthKey(r.date),heures:0,sup:0}; a[k].heures+=Number(r.hours); a[k].sup+=Number(r.overtime||0); return a;},{})); return <><Header title="Rapports semaine / mois / année" desc="Export CSV disponible pour Excel."/><button className="primary" onClick={csv}>Télécharger CSV</button><div className="card"><Table rows={summary} cols={['employe','mois','heures','sup']}/></div></> }
function Approval({data,setData}){ const upd=(id,status)=>setData(d=>({...d,timeEntries:d.timeEntries.map(x=>x.id===id?{...x,status}:x)})); return <><Header title="Validation admin" desc="Valider ou refuser les heures des employés."/><div className="card">{data.timeEntries.map(r=><div className="line" key={r.id}><span>{r.date} — {r.employeeName} — {r.project} — {r.hours}h</span><b>{r.status}</b><button onClick={()=>upd(r.id,'approved')}>Valider</button><button onClick={()=>upd(r.id,'rejected')}>Refuser</button></div>)}</div></> }
function Employees({data,setData}){ const [f,setF]=useState({name:'',email:'',role:'employee'}); const add=e=>{e.preventDefault(); if(!f.email) return; setData(d=>({...d,employees:[...d.employees,{id:uid(),...f,password:DEFAULT_PASSWORD,mustChangePassword:true,active:true,createdAt:new Date().toISOString()}]})); setF({name:'',email:'',role:'employee'});}; const toggle=id=>setData(d=>({...d,employees:d.employees.map(x=>x.id===id?{...x,active:!x.active}:x)})); return <><Header title="Employés" desc="Ajouter ou désactiver un employé. Mot de passe initial : 1234."/><form className="card formGrid" onSubmit={add}><input placeholder="Nom" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option value="employee">Employé</option><option value="admin">Admin</option></select><button className="primary"><Plus size={16}/>Ajouter</button></form><div className="card"><Table rows={data.employees} cols={['name','email','role','active']}/>{data.employees.map(e=><button key={e.id} onClick={()=>toggle(e.id)}>{e.active?'Désactiver ':'Réactiver '}{e.name}</button>)}</div></> }
function Absences({user,data,setData}){ const [f,setF]=useState({type:'Vacances',from:today(),to:today(),note:''}); const add=e=>{e.preventDefault(); setData(d=>({...d,absences:[...d.absences,{id:uid(),...f,employeeId:user.id,employeeName:user.name,status:'pending'}]}));}; const rows=data.absences.filter(x=>user.role==='admin'||x.employeeId===user.id); return <><Header title="Vacances / congés" desc="Demandes d'absence avec validation admin."/><form className="card formGrid" onSubmit={add}><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>Vacances</option><option>Congé</option><option>Maladie</option><option>Autre</option></select><input type="date" value={f.from} onChange={e=>setF({...f,from:e.target.value})}/><input type="date" value={f.to} onChange={e=>setF({...f,to:e.target.value})}/><input placeholder="Note" value={f.note} onChange={e=>setF({...f,note:e.target.value})}/><button className="primary">Demander</button></form><div className="card"><Table rows={rows} cols={['employeeName','type','from','to','status','note']}/></div></> }
function AbsenceCalendar({data}){ return <><Header title="Calendrier des absences" desc="Vue simple des absences enregistrées."/><div className="card calendar">{data.absences.map(a=><div className="absence" key={a.id}><b>{a.from} → {a.to}</b><span>{a.employeeName} — {a.type} — {a.status}</span></div>)}</div></> }
function Expenses({user,data,setData}){ const [f,setF]=useState({date:today(),label:'',amount:'',photo:''}); const add=async e=>{e.preventDefault(); setData(d=>({...d,expenses:[...d.expenses,{id:uid(),...f,amount:Number(f.amount),employeeId:user.id,employeeName:user.name,status:'pending'}]})); setF({date:today(),label:'',amount:'',photo:''});}; const photo=async e=>{const file=e.target.files[0]; if(file) setF({...f,photo:await fileToDataUrl(file)});}; const rows=data.expenses.filter(x=>user.role==='admin'||x.employeeId===user.id); return <><Header title="Notes de frais" desc="Ajouter les tickets / quittances en photo."/><form className="card formGrid" onSubmit={add}><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/><input placeholder="Libellé" value={f.label} onChange={e=>setF({...f,label:e.target.value})}/><input type="number" step="0.05" placeholder="Montant CHF" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><label className="file"><ImageIcon size={16}/>Photo ticket<input type="file" accept="image/*" onChange={photo}/></label><button className="primary">Ajouter</button></form><div className="card"><Table rows={rows} cols={['date','employeeName','label','amount','status']}/>{rows.filter(x=>x.photo).map(x=><img key={x.id} className="thumb" src={x.photo}/>)}</div></> }
function Mileage({user,data,setData}){ const [f,setF]=useState({date:today(),from:'',to:'',km:''}); const add=e=>{e.preventDefault(); setData(d=>({...d,mileage:[...d.mileage,{id:uid(),...f,km:Number(f.km),employeeId:user.id,employeeName:user.name}]}));}; const rows=data.mileage.filter(x=>user.role==='admin'||x.employeeId===user.id); return <><Header title="Suivi des kilomètres" desc="Trajets professionnels par employé."/><form className="card formGrid" onSubmit={add}><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/><input placeholder="Départ" value={f.from} onChange={e=>setF({...f,from:e.target.value})}/><input placeholder="Arrivée" value={f.to} onChange={e=>setF({...f,to:e.target.value})}/><input type="number" placeholder="Km" value={f.km} onChange={e=>setF({...f,km:e.target.value})}/><button className="primary">Ajouter</button></form><div className="card"><Table rows={rows} cols={['date','employeeName','from','to','km']}/></div></> }
function Payslips({user,data,setData}){ const [f,setF]=useState({employeeId:data.employees.find(e=>e.role==='employee')?.id||'',month:monthKey(today()),fileName:'',fileData:''}); const upload=async e=>{const file=e.target.files[0]; if(file) setF({...f,fileName:file.name,fileData:await fileToDataUrl(file)});}; const add=e=>{e.preventDefault(); const emp=data.employees.find(x=>x.id===f.employeeId); setData(d=>({...d,payslips:[...d.payslips,{id:uid(),...f,employeeName:emp?.name||''}]}));}; const rows=data.payslips.filter(x=>user.role==='admin'||x.employeeId===user.id); return <><Header title="Fiches de salaire" desc="L'admin insère les fiches, l'employé peut les télécharger."/>{user.role==='admin'&&<form className="card formGrid" onSubmit={add}><select value={f.employeeId} onChange={e=>setF({...f,employeeId:e.target.value})}>{data.employees.filter(e=>e.role!=='admin').map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select><input type="month" value={f.month} onChange={e=>setF({...f,month:e.target.value})}/><label className="file"><Upload size={16}/>PDF fiche<input type="file" accept="application/pdf" onChange={upload}/></label><button className="primary">Publier</button></form>}<div className="card">{rows.map(p=><div className="line" key={p.id}><span>{p.month} — {p.employeeName} — {p.fileName}</span><a className="button" href={p.fileData} download={p.fileName}>Télécharger</a></div>)}</div></> }
function Table({rows,cols}){ if(!rows?.length) return <p className="muted">Aucune donnée pour le moment.</p>; return <div className="table"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{String(r[c] ?? '')}</td>)}</tr>)}</tbody></table></div> }
createRoot(document.getElementById('root')).render(<App/>);
